"""Add AITrace model

Revision ID: e9f3f9f6c02b
Revises: f32b9dee3929
Create Date: 2026-07-12 11:41:11.340569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9f3f9f6c02b'
down_revision: Union[str, None] = 'f32b9dee3929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('raw_llm_response', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_traces_conversation_id'), 'ai_traces', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_traces_conversation_id'), table_name='ai_traces')
    op.drop_table('ai_traces')
    # ### end Alembic commands ###
