"""Add ca_profile_id to clients

Revision ID: ea998a3bb2e0
Revises: 5384821d750f
Create Date: 2026-07-13 01:54:49.872199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea998a3bb2e0'
down_revision: Union[str, None] = '5384821d750f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM clients')
    op.add_column('clients', sa.Column('ca_profile_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_clients_ca_profile_id'), 'clients', ['ca_profile_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'ca_profiles', ['ca_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_ca_profile_id'), table_name='clients')
    op.drop_column('clients', 'ca_profile_id')
    # ### end Alembic commands ###
