"""Add Invoice model

Revision ID: efc6fe01da2f
Revises: 20260710_0002
Create Date: 2026-07-11 18:24:36.617971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc6fe01da2f'
down_revision: Union[str, None] = '20260710_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('success_fee_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('success_fee_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_due_date', sa.String(length=255), nullable=True),
    sa.Column('payment_received_date', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.drop_constraint(op.f('uq_ca_profiles_membership_number'), 'ca_profiles', type_='unique')
    op.drop_constraint(op.f('uq_ca_profiles_user_id'), 'ca_profiles', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_ca_profiles_user_id'), 'ca_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_ca_profiles_membership_number'), 'ca_profiles', ['membership_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
