"""Add pgvector and embeddings

Revision ID: f32b9dee3929
Revises: ed6709689bde
Create Date: 2026-07-11 22:57:57.774920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f32b9dee3929'
down_revision: Union[str, None] = 'ed6709689bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column('knowledge_chunks', sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding_provider', sa.String(length=255), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding_latency_ms', sa.Integer(), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding_checksum', sa.String(length=255), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'embedding_version')
    op.drop_column('knowledge_chunks', 'embedding_checksum')
    op.drop_column('knowledge_chunks', 'embedding_generated_at')
    op.drop_column('knowledge_chunks', 'embedding_latency_ms')
    op.drop_column('knowledge_chunks', 'embedding_provider')
    op.drop_column('knowledge_chunks', 'embedding_dimension')
    op.drop_column('knowledge_chunks', 'embedding_model')
    op.drop_column('knowledge_chunks', 'embedding_vector')
    # ### end Alembic commands ###
